version: '2.3'
services:
  face-recognition:
    image: ichizero/face-recognition:latest
    runtime: nvidia
    container_name: entrance-monitor
    restart: always
    ports:
      - "5001:5001"
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./proxy.env
      - ./secret.env
    volumes:
      - ./:/workspace/face-recognition
    working_dir: /workspace/face-recognition
    entrypoint: ./start.sh
