version: '2.3'
services:
  face-recognition:
    image: ichizero/face-recognition:latest
    runtime: nvidia
    container_name: face-recognition
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./proxy.env
      - ./secret.env
    volumes:
      - ./:/workspace/face-recognition
    working_dir: /workspace/face-recognition
    entrypoint: python monitoring.py --url=$CAM_URL --face=./faces/ --tol=0.4 --lt=$LINE_ACCESS_TOKEN --lu=$LINE_USER_ID
